### PR TITLE
Fixed distributed velocity halo filling error that was causing MPI memory issues

### LINKED ISSUE #2: Idealized time-series representing prescribed atmospheric state
To motivate fleshing out the user-interface for the `ThermodynamicSeaIce` model, we'd like to develop an idealized time-dependent scenario representing ice growth/melting (with time-evolving atmospheric state / radiation conditions, and time-evolving ocean state).

### PR DESCRIPTION
**Pull request by taimoorsohail**
## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by simone-silvestri — APPROVED** [review]

File: src/sea_ice_model.jl [hunk 1]
```diff
@@ -86,13 +92,18 @@ function SeaIceModel(grid;
         # an extended split explicit momentum equation
         if dynamics isa ExtendedSplitExplicitMomentumEquation
             old_halos = halo_size(grid)
-            Nsubsteps = length(dynamics.solver.substeps)
+            raw_substeps = dynamics.solver.substeps
+            Nsubsteps = raw_substeps isa Integer ? raw_substeps : length(raw_substeps)
```
Comment (simone-silvestri) [inline src/sea_ice_model.jl]: I think it can only be an Integer
